import React, { useState } from 'react';
import { BookOpen, Search, X, Scale, FileText, CheckCircle2, Shield } from 'lucide-react';

interface BNSModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const BNSModal: React.FC<BNSModalProps> = ({ isOpen, onClose }) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedTab, setSelectedTab] = useState<'BNSS_PROCEDURAL' | 'BNS_PENAL'>('BNSS_PROCEDURAL');

  // COMPLETE 531 SECTIONS OF BHARATIYA NAGARIK SURAKSHA SANHITA (BNSS 2023)
  const bnssAllSections = [
    { section: 1, title: 'Short title, extent and commencement', chapter: 'Chapter I: Preliminary' },
    { section: 2, title: 'Definitions (Cognizable, Bailable, Victim, Audio-Video Media)', chapter: 'Chapter I: Preliminary' },
    { section: 3, title: 'Construction of references', chapter: 'Chapter I: Preliminary' },
    { section: 4, title: 'Trial of offences under Bharatiya Nyaya Sanhita, 2023 and other laws', chapter: 'Chapter I: Preliminary' },
    { section: 5, title: 'Saving clause', chapter: 'Chapter I: Preliminary' },
    { section: 6, title: 'Classes of Criminal Courts', chapter: 'Chapter II: Constitution of Criminal Courts' },
    { section: 7, title: 'Territorial divisions', chapter: 'Chapter II: Constitution of Criminal Courts' },
    { section: 8, title: 'Court of Session', chapter: 'Chapter II: Constitution of Criminal Courts' },
    { section: 9, title: 'Courts of Judicial Magistrates', chapter: 'Chapter II: Constitution of Criminal Courts' },
    { section: 10, title: 'Chief Judicial Magistrate and Additional Chief Judicial Magistrate', chapter: 'Chapter II: Constitution of Criminal Courts' },
    { section: 11, title: 'Special Judicial Magistrates', chapter: 'Chapter II: Constitution of Criminal Courts' },
    { section: 12, title: 'Local Jurisdiction of Judicial Magistrates', chapter: 'Chapter II: Constitution of Criminal Courts' },
    { section: 13, title: 'Subordination of Judicial Magistrates', chapter: 'Chapter II: Constitution of Criminal Courts' },
    { section: 14, title: 'Executive Magistrates', chapter: 'Chapter II: Constitution of Criminal Courts' },
    { section: 15, title: 'Special Executive Magistrates', chapter: 'Chapter II: Constitution of Criminal Courts' },
    { section: 16, title: 'Local Jurisdiction of Executive Magistrates', chapter: 'Chapter II: Constitution of Criminal Courts' },
    { section: 17, title: 'Subordination of Executive Magistrates', chapter: 'Chapter II: Constitution of Criminal Courts' },
    { section: 18, title: 'Public Prosecutors', chapter: 'Chapter II: Constitution of Criminal Courts' },
    { section: 19, title: 'Assistant Public Prosecutors', chapter: 'Chapter II: Constitution of Criminal Courts' },
    { section: 20, title: 'Directorate of Prosecution', chapter: 'Chapter II: Constitution of Criminal Courts' },
    { section: 21, title: 'Courts by which offences are triable', chapter: 'Chapter III: Power of Courts' },
    { section: 22, title: 'Sentences which High Courts and Sessions Judges may pass', chapter: 'Chapter III: Power of Courts' },
    { section: 23, title: 'Sentences which Magistrates may pass', chapter: 'Chapter III: Power of Courts' },
    { section: 24, title: 'Sentence of imprisonment in default of fine', chapter: 'Chapter III: Power of Courts' },
    { section: 25, title: 'Sentence in cases of conviction of several offences at one trial', chapter: 'Chapter III: Power of Courts' },
    { section: 26, title: 'Mode of conferring powers', chapter: 'Chapter III: Power of Courts' },
    { section: 27, title: 'Powers of officers appointed', chapter: 'Chapter III: Power of Courts' },
    { section: 28, title: 'Withdrawal of powers', chapter: 'Chapter III: Power of Courts' },
    { section: 29, title: 'Powers of Judges and Magistrates exercisable by successors-in-office', chapter: 'Chapter III: Power of Courts' },
    { section: 30, title: 'Powers of superior officers of police', chapter: 'Chapter IV: Powers of Superior Police Officers' },
    { section: 31, title: 'Public when to assist Magistrates and police', chapter: 'Chapter V: Public Assistance' },
    { section: 32, title: 'Aid to person, other than police officer, executing warrant', chapter: 'Chapter V: Public Assistance' },
    { section: 33, title: 'Public to give information of certain offences', chapter: 'Chapter V: Public Assistance' },
    { section: 34, title: 'Duty of village officers to make report of certain offences', chapter: 'Chapter V: Public Assistance' },
    { section: 35, title: 'When police may arrest without warrant', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 36, title: 'Procedure of arrest and duties of officer making arrest', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 37, title: 'Designated police officer in every district and station', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 38, title: 'Right of arrested person to meet an advocate of choice during interrogation', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 39, title: 'Arrest on refusal to give name and residence', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 40, title: 'Arrest by private person and procedure on such arrest', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 41, title: 'Arrest by Magistrate', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 42, title: 'Protection of members of Armed Forces from arrest', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 43, title: 'Arrest how made', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 44, title: 'Search of place entered by person sought to be arrested', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 45, title: 'Pursuit of offenders into other jurisdictions', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 46, title: 'No unnecessary restraint', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 47, title: 'Person arrested to be informed of grounds of arrest and right to bail', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 48, title: 'Obligation to inform relative/friend about arrest', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 49, title: 'Search of arrested person', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 50, title: 'Power to seize offensive weapons', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 51, title: 'Examination of accused by medical practitioner at request of police', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 52, title: 'Examination of person accused of rape by medical practitioner', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 53, title: 'Examination of arrested person by medical officer', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 54, title: 'Identification of person arrested', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 55, title: 'Procedure when police officer deputes subordinate to arrest without warrant', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 56, title: 'Health and safety of arrested person', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 57, title: 'Person arrested to be taken before Magistrate or officer in charge of station', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 58, title: 'Person arrested not to be detained more than twenty-four hours', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 59, title: 'Police to report apprehensions', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 60, title: 'Discharge of person apprehended', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 61, title: 'Power, on escape, to pursue and retake', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 62, title: 'Arrest to be made strictly according to Sanhita', chapter: 'Chapter VI: Arrest of Persons' },
    { section: 63, title: 'Form of summons', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 64, title: 'Summons how served (Electronic Summons included)', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 65, title: 'Service of summons on corporate bodies, firms, and societies', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 66, title: 'Service when persons summoned cannot be found', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 67, title: 'Procedure when service cannot be effected as before provided', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 68, title: 'Service on Government servant', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 69, title: 'Service of summons outside local limits', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 70, title: 'Proof of service in such cases and when serving officer not present', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 71, title: 'Service of summons on witness', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 72, title: 'Form of warrant of arrest and duration', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 73, title: 'Power to direct security to be taken', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 74, title: 'Warrants to whom directed', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 75, title: 'Warrant may be directed to any person', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 76, title: 'Warrant directed to police officer', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 77, title: 'Notification of substance of warrant', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 78, title: 'Person arrested to be brought before Court without delay', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 79, title: 'Where warrant may be executed', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 80, title: 'Warrant forwarded for execution outside jurisdiction', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 81, title: 'Warrant directed to police officer for execution outside jurisdiction', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 82, title: 'Procedure on arrest of person against whom warrant issued', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 83, title: 'Procedure by Magistrate before whom such person arrested is brought', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 84, title: 'Proclamation for person absconding', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 85, title: 'Attachment of property of person absconding', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 86, title: 'Identification and attachment of property of proclaimed person', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 87, title: 'Claims and objections to attachment', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 88, title: 'Release, sale and restoration of attached property', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 89, title: 'Appeal from order rejecting application for restoration of attached property', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 90, title: 'Issue of warrant in lieu of, or in addition to, summons', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 91, title: 'Power to take bond or bail bond for appearance', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 92, title: 'Arrest on breach of bond or bail bond for appearance', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 93, title: 'Provisions generally applicable to summons and warrants of arrest', chapter: 'Chapter VII: Summons & Warrants' },
    { section: 94, title: 'Summons to produce document or other thing', chapter: 'Chapter VIII: Search & Seizure' },
    { section: 95, title: 'Procedure as to letters and telegrams', chapter: 'Chapter VIII: Search & Seizure' },
    { section: 96, title: 'When search-warrant may be issued', chapter: 'Chapter VIII: Search & Seizure' },
    { section: 97, title: 'Search of place suspected to contain stolen property, forged documents', chapter: 'Chapter VIII: Search & Seizure' },
    { section: 98, title: 'Power to declare certain publications forfeited and issue search-warrants', chapter: 'Chapter VIII: Search & Seizure' },
    { section: 99, title: 'Application to High Court to set aside declaration of forfeiture', chapter: 'Chapter VIII: Search & Seizure' },
    { section: 100, title: 'Search for persons wrongfully confined', chapter: 'Chapter VIII: Search & Seizure' },
    { section: 101, title: 'Power to compel restoration of abducted females', chapter: 'Chapter VIII: Search & Seizure' },
    { section: 102, title: 'Direction of search-warrants', chapter: 'Chapter VIII: Search & Seizure' },
    { section: 103, title: 'Persons in charge of closed place to allow search', chapter: 'Chapter VIII: Search & Seizure' },
    { section: 104, title: 'Disposal of things found in search beyond jurisdiction', chapter: 'Chapter VIII: Search & Seizure' },
    { section: 105, title: 'Recording of search and seizure through audio video electronic means', chapter: 'Chapter VIII: Search & Seizure (DIGITAL MANDATE)' },
    { section: 106, title: 'Power of police officer to seize certain property', chapter: 'Chapter VIII: Search & Seizure' },
    { section: 107, title: 'Attachment, forfeiture or restoration of property', chapter: 'Chapter VIII: Search & Seizure' },
    { section: 108, title: 'Magistrate may direct search in presence', chapter: 'Chapter VIII: Search & Seizure' },
    { section: 109, title: 'Power to impound document produced', chapter: 'Chapter VIII: Search & Seizure' },
    { section: 110, title: 'Reciprocal arrangements regarding processes', chapter: 'Chapter VIII: Search & Seizure' },
    { section: 111, title: 'Definitions (Property derived from crime)', chapter: 'Chapter IX: Asset Attachment' },
    { section: 112, title: 'Letter of request for investigation outside India', chapter: 'Chapter IX: Asset Attachment' },
    { section: 113, title: 'Letter of request from outside India for investigation in India', chapter: 'Chapter IX: Asset Attachment' },
    { section: 114, title: 'Assistance in securing transfer of persons', chapter: 'Chapter IX: Asset Attachment' },
    { section: 115, title: 'Assistance in relation to attachment/forfeiture of property', chapter: 'Chapter IX: Asset Attachment' },
    { section: 116, title: 'Identifying unlawfully acquired property', chapter: 'Chapter IX: Asset Attachment' },
    { section: 117, title: 'Seizure or attachment of property', chapter: 'Chapter IX: Asset Attachment' },
    { section: 118, title: 'Management of properties seized or forfeited', chapter: 'Chapter IX: Asset Attachment' },
    { section: 119, title: 'Notice of forfeiture of property', chapter: 'Chapter IX: Asset Attachment' },
    { section: 120, title: 'Forfeiture of property in certain cases', chapter: 'Chapter IX: Asset Attachment' },
    { section: 121, title: 'Fine in lieu of forfeiture', chapter: 'Chapter IX: Asset Attachment' },
    { section: 122, title: 'Certain transfers to be null and void', chapter: 'Chapter IX: Asset Attachment' },
    { section: 123, title: 'Procedure in respect of letter of request', chapter: 'Chapter IX: Asset Attachment' },
    { section: 124, title: 'Application of Chapter', chapter: 'Chapter IX: Asset Attachment' },
    { section: 125, title: 'Security for keeping peace on conviction', chapter: 'Chapter X: Maintenance of Peace' },
    { section: 126, title: 'Security for keeping peace in other cases', chapter: 'Chapter X: Maintenance of Peace' },
    { section: 127, title: 'Security for good behaviour from persons disseminating seditious matter', chapter: 'Chapter X: Maintenance of Peace' },
    { section: 128, title: 'Security for good behaviour from suspected persons', chapter: 'Chapter X: Maintenance of Peace' },
    { section: 129, title: 'Security for good behaviour from habitual offenders', chapter: 'Chapter X: Maintenance of Peace' },
    { section: 130, title: 'Order to be made by Magistrate', chapter: 'Chapter X: Maintenance of Peace' },
    { section: 131, title: 'Procedure in respect of person present in Court', chapter: 'Chapter X: Maintenance of Peace' },
    { section: 132, title: 'Summons or warrant in case of person not present', chapter: 'Chapter X: Maintenance of Peace' },
    { section: 133, title: 'Copy of order to accompany summons or warrant', chapter: 'Chapter X: Maintenance of Peace' },
    { section: 134, title: 'Power to dispense with personal attendance', chapter: 'Chapter X: Maintenance of Peace' },
    { section: 135, title: 'Inquiry as to truth of information', chapter: 'Chapter X: Maintenance of Peace' },
    { section: 136, title: 'Order to give security', chapter: 'Chapter X: Maintenance of Peace' },
    { section: 137, title: 'Discharge of person informed against', chapter: 'Chapter X: Maintenance of Peace' },
    { section: 138, title: 'Commencement of period for security', chapter: 'Chapter X: Maintenance of Peace' },
    { section: 139, title: 'Contents of bond', chapter: 'Chapter X: Maintenance of Peace' },
    { section: 140, title: 'Power to reject sureties', chapter: 'Chapter X: Maintenance of Peace' },
    { section: 141, title: 'Imprisonment in default of security', chapter: 'Chapter X: Maintenance of Peace' },
    { section: 142, title: 'Power to release persons imprisoned for failing to give security', chapter: 'Chapter X: Maintenance of Peace' },
    { section: 143, title: 'Security for unexpired period of bond', chapter: 'Chapter X: Maintenance of Peace' },
    { section: 144, title: 'Order for maintenance of wives, children and parents', chapter: 'Chapter XI: Maintenance Order' },
    { section: 145, title: 'Procedure for maintenance claim', chapter: 'Chapter XI: Maintenance Order' },
    { section: 146, title: 'Alteration in maintenance allowance', chapter: 'Chapter XI: Maintenance Order' },
    { section: 147, title: 'Enforcement of order of maintenance', chapter: 'Chapter XI: Maintenance Order' },
    { section: 148, title: 'Dispersal of assembly by use of civil force', chapter: 'Chapter XII: Public Order' },
    { section: 149, title: 'Use of armed forces to disperse assembly', chapter: 'Chapter XII: Public Order' },
    { section: 150, title: 'Power of armed force officers to disperse assembly', chapter: 'Chapter XII: Public Order' },
    { section: 151, title: 'Protection against prosecution for acts done under sections 148-150', chapter: 'Chapter XII: Public Order' },
    { section: 152, title: 'Conditional order for removal of nuisance', chapter: 'Chapter XII: Public Order' },
    { section: 153, title: 'Service or notification of order', chapter: 'Chapter XII: Public Order' },
    { section: 154, title: 'Person to whom order addressed to obey or show cause', chapter: 'Chapter XII: Public Order' },
    { section: 155, title: 'Penalty for failure to comply', chapter: 'Chapter XII: Public Order' },
    { section: 156, title: 'Procedure where existence of public right is denied', chapter: 'Chapter XII: Public Order' },
    { section: 157, title: 'Procedure where person appears to show cause', chapter: 'Chapter XII: Public Order' },
    { section: 158, title: 'Local investigation and examination of expert', chapter: 'Chapter XII: Public Order' },
    { section: 159, title: 'Power of Magistrate to furnish written instructions', chapter: 'Chapter XII: Public Order' },
    { section: 160, title: 'Procedure on order being made absolute', chapter: 'Chapter XII: Public Order' },
    { section: 161, title: 'Injunction pending inquiry', chapter: 'Chapter XII: Public Order' },
    { section: 162, title: 'Magistrate may prohibit repetition of public nuisance', chapter: 'Chapter XII: Public Order' },
    { section: 163, title: 'Order in urgent cases of nuisance or apprehended danger (Old Sec 144)', chapter: 'Chapter XII: Public Order' },
    { section: 164, title: 'Dispute concerning land or water likely to cause breach of peace', chapter: 'Chapter XII: Public Order' },
    { section: 165, title: 'Power to attach subject of dispute and appoint receiver', chapter: 'Chapter XII: Public Order' },
    { section: 166, title: 'Dispute concerning right of use of land or water', chapter: 'Chapter XII: Public Order' },
    { section: 167, title: 'Local inquiry', chapter: 'Chapter XII: Public Order' },
    { section: 168, title: 'Police to prevent cognizable offences', chapter: 'Chapter XIII: Preventive Action' },
    { section: 169, title: 'Information of design to commit cognizable offences', chapter: 'Chapter XIII: Preventive Action' },
    { section: 170, title: 'Arrest to prevent commission of cognizable offences', chapter: 'Chapter XIII: Preventive Action' },
    { section: 171, title: 'Prevention of injury to public property', chapter: 'Chapter XIII: Preventive Action' },
    { section: 172, title: 'Persons bound to conform to lawful directions of police', chapter: 'Chapter XIII: Preventive Action' },
    { section: 173, title: 'Information in cognizable cases (MANDATORY ELECTRONIC FIR FILING)', chapter: 'Chapter XIV: Investigation (CORE FIR RULE)' },
    { section: 174, title: 'Information as to non-cognizable cases and investigation', chapter: 'Chapter XIV: Investigation' },
    { section: 175, title: 'Police officer power to investigate cognizable case', chapter: 'Chapter XIV: Investigation' },
    { section: 176, title: 'Procedure for investigation & mandatory audio-video forensic collection', chapter: 'Chapter XIV: Investigation' },
    { section: 177, title: 'Report how submitted', chapter: 'Chapter XIV: Investigation' },
    { section: 178, title: 'Power to hold investigation or preliminary inquiry', chapter: 'Chapter XIV: Investigation' },
    { section: 179, title: 'Police officer power to require attendance of witnesses', chapter: 'Chapter XIV: Investigation' },
    { section: 180, title: 'Examination of witnesses by police', chapter: 'Chapter XIV: Investigation' },
    { section: 181, title: 'Statements to police and use thereof', chapter: 'Chapter XIV: Investigation' },
    { section: 182, title: 'No inducement to be offered', chapter: 'Chapter XIV: Investigation' },
    { section: 183, title: 'Recording of confessions and statements by Magistrate', chapter: 'Chapter XIV: Investigation' },
    { section: 184, title: 'Medical examination of victim of rape', chapter: 'Chapter XIV: Investigation' },
    { section: 185, title: 'Search by police officer', chapter: 'Chapter XIV: Investigation' },
    { section: 186, title: 'When officer in charge of police station may require another to issue search-warrant', chapter: 'Chapter XIV: Investigation' },
    { section: 187, title: 'Procedure when investigation cannot be completed in twenty-four hours', chapter: 'Chapter XIV: Investigation' },
    { section: 188, title: 'Report of investigation by subordinate police officer', chapter: 'Chapter XIV: Investigation' },
    { section: 189, title: 'Release of accused when evidence deficient', chapter: 'Chapter XIV: Investigation' },
    { section: 190, title: 'Cases to be sent to Magistrate when evidence is sufficient', chapter: 'Chapter XIV: Investigation' },
    { section: 191, title: 'Complainant and witnesses not to be required to accompany police officer', chapter: 'Chapter XIV: Investigation' },
    { section: 192, title: 'Diary of proceedings in investigation (Case Diary)', chapter: 'Chapter XIV: Investigation' },
    { section: 193, title: 'Report of police officer on completion of investigation (Charge Sheet)', chapter: 'Chapter XIV: Investigation' },
    { section: 194, title: 'Police to enquire and report on suicide', chapter: 'Chapter XIV: Investigation' },
    { section: 195, title: 'Power to summon persons for inquest', chapter: 'Chapter XIV: Investigation' },
    { section: 196, title: 'Inquiry by Magistrate into cause of death', chapter: 'Chapter XIV: Investigation' },
    { section: 197, title: 'Ordinary place of inquiry and trial', chapter: 'Chapter XV: Jurisdiction of Courts' },
    { section: 198, title: 'Place of inquiry or trial', chapter: 'Chapter XV: Jurisdiction of Courts' },
    { section: 199, title: 'Offence triable where act is done or consequence ensues', chapter: 'Chapter XV: Jurisdiction of Courts' },
    { section: 200, title: 'Place of trial where act is offence by relation to other offence', chapter: 'Chapter XV: Jurisdiction of Courts' },
    { section: 201, title: 'Place of trial in case of certain offences', chapter: 'Chapter XV: Jurisdiction of Courts' },
    { section: 202, title: 'Offences committed by electronic communications, letters', chapter: 'Chapter XV: Jurisdiction of Courts' },
    { section: 203, title: 'Offence committed on journey or voyage', chapter: 'Chapter XV: Jurisdiction of Courts' },
    { section: 204, title: 'Place of trial for offences triable together', chapter: 'Chapter XV: Jurisdiction of Courts' },
    { section: 205, title: 'Power to order cases to be tried in different sessions divisions', chapter: 'Chapter XV: Jurisdiction of Courts' },
    { section: 206, title: 'High Court to decide district in case of doubt', chapter: 'Chapter XV: Jurisdiction of Courts' },
    { section: 207, title: 'Summons/warrant for offence committed beyond jurisdiction', chapter: 'Chapter XV: Jurisdiction of Courts' },
    { section: 208, title: 'Offence committed outside India', chapter: 'Chapter XV: Jurisdiction of Courts' },
    { section: 209, title: 'Receipt of evidence relating to offences committed outside India', chapter: 'Chapter XV: Jurisdiction of Courts' },
    { section: 210, title: 'Cognizance of offences by Magistrate', chapter: 'Chapter XVI: Cognizance of Offences' },
    { section: 211, title: 'Transfer on application of accused', chapter: 'Chapter XVI: Cognizance of Offences' },
    { section: 212, title: 'Making over of cases to Magistrates', chapter: 'Chapter XVI: Cognizance of Offences' },
    { section: 213, title: 'Cognizance of offences by Court of Session', chapter: 'Chapter XVI: Cognizance of Offences' },
    { section: 214, title: 'Additional Sessions Judges to try cases made over', chapter: 'Chapter XVI: Cognizance of Offences' },
    { section: 215, title: 'Prosecution for contempt of lawful authority of public servants', chapter: 'Chapter XVI: Cognizance of Offences' },
    { section: 216, title: 'Procedure for witnesses in case of threatening', chapter: 'Chapter XVI: Cognizance of Offences' },
    { section: 217, title: 'Prosecution for offences against State and criminal conspiracy', chapter: 'Chapter XVI: Cognizance of Offences' },
    { section: 218, title: 'Prosecution of Judges and public servants', chapter: 'Chapter XVI: Cognizance of Offences' },
    { section: 219, title: 'Prosecution for offences against marriage', chapter: 'Chapter XVI: Cognizance of Offences' },
    { section: 220, title: 'Prosecution of offences under Section 85 of BNS 2023 (Dowry Cruelty)', chapter: 'Chapter XVI: Cognizance of Offences' },
    { section: 221, title: 'Cognizance of offence', chapter: 'Chapter XVI: Cognizance of Offences' },
    { section: 222, title: 'Prosecution for defamation', chapter: 'Chapter XVI: Cognizance of Offences' },
    { section: 223, title: 'Examination of complainant', chapter: 'Chapter XVII: Complaints to Magistrates' },
    { section: 224, title: 'Procedure by Magistrate not competent to take cognizance', chapter: 'Chapter XVII: Complaints to Magistrates' },
    { section: 225, title: 'Postponement of issue of process', chapter: 'Chapter XVII: Complaints to Magistrates' },
    { section: 226, title: 'Dismissal of complaint', chapter: 'Chapter XVII: Complaints to Magistrates' },
    { section: 227, title: 'Issue of process', chapter: 'Chapter XVIII: Process Commencement' },
    { section: 228, title: 'Magistrate may dispense with personal attendance of accused', chapter: 'Chapter XVIII: Process Commencement' },
    { section: 229, title: 'Special summons in cases of petty offence', chapter: 'Chapter XVIII: Process Commencement' },
    { section: 230, title: 'Supply to accused of copy of police report and other documents', chapter: 'Chapter XVIII: Process Commencement' },
    { section: 231, title: 'Supply of copies of statements to accused in Session cases', chapter: 'Chapter XVIII: Process Commencement' },
    { section: 232, title: 'Commitment of case to Court of Session', chapter: 'Chapter XVIII: Process Commencement' },
    { section: 233, title: 'Procedure when complaint case and police investigation exist for same offence', chapter: 'Chapter XVIII: Process Commencement' },
    { section: 234, title: 'Contents of charge', chapter: 'Chapter XIX: Charge Framing' },
    { section: 235, title: 'Particulars as to time, place and person', chapter: 'Chapter XIX: Charge Framing' },
    { section: 236, title: 'When manner of committing offence must be stated', chapter: 'Chapter XIX: Charge Framing' },
    { section: 237, title: 'Words in charge taken in sense of law', chapter: 'Chapter XIX: Charge Framing' },
    { section: 238, title: 'Effect of errors in charge', chapter: 'Chapter XIX: Charge Framing' },
    { section: 239, title: 'Court may alter charge', chapter: 'Chapter XIX: Charge Framing' },
    { section: 240, title: 'Recall of witnesses when charge altered', chapter: 'Chapter XIX: Charge Framing' },
    { section: 241, title: 'Separate charges for distinct offences', chapter: 'Chapter XIX: Charge Framing' },
    { section: 242, title: 'Offences of same kind within year charged together', chapter: 'Chapter XIX: Charge Framing' },
    { section: 243, title: 'Trial for more than one offence', chapter: 'Chapter XIX: Charge Framing' },
    { section: 244, title: 'Where doubtful what offence has been committed', chapter: 'Chapter XIX: Charge Framing' },
    { section: 245, title: 'When offence proved included in offence charged', chapter: 'Chapter XIX: Charge Framing' },
    { section: 246, title: 'What persons may be charged jointly', chapter: 'Chapter XIX: Charge Framing' },
    { section: 247, title: 'Withdrawal of remaining charges on conviction', chapter: 'Chapter XIX: Charge Framing' },
    { section: 248, title: 'Trial to be conducted by Public Prosecutor', chapter: 'Chapter XX: Sessions Trial' },
    { section: 249, title: 'Opening case for prosecution', chapter: 'Chapter XX: Sessions Trial' },
    { section: 250, title: 'Discharge of accused in Sessions Trial', chapter: 'Chapter XX: Sessions Trial' },
    { section: 251, title: 'Framing of charge', chapter: 'Chapter XX: Sessions Trial' },
    { section: 252, title: 'Conviction on plea of guilty', chapter: 'Chapter XX: Sessions Trial' },
    { section: 253, title: 'Date for prosecution evidence', chapter: 'Chapter XX: Sessions Trial' },
    { section: 254, title: 'Evidence for prosecution', chapter: 'Chapter XX: Sessions Trial' },
    { section: 255, title: 'Acquittal in Sessions Trial', chapter: 'Chapter XX: Sessions Trial' },
    { section: 256, title: 'Entering upon defence', chapter: 'Chapter XX: Sessions Trial' },
    { section: 257, title: 'Arguments', chapter: 'Chapter XX: Sessions Trial' },
    { section: 258, title: 'Judgment of acquittal or conviction', chapter: 'Chapter XX: Sessions Trial' },
    { section: 259, title: 'Previous conviction', chapter: 'Chapter XX: Sessions Trial' },
    { section: 260, title: 'Procedure in cases under sub-section (2) of section 222', chapter: 'Chapter XX: Sessions Trial' },
    { section: 261, title: 'Compliance with section 230', chapter: 'Chapter XXI: Warrant Cases Trial' },
    { section: 262, title: 'When accused shall be discharged', chapter: 'Chapter XXI: Warrant Cases Trial' },
    { section: 263, title: 'Framing of charge', chapter: 'Chapter XXI: Warrant Cases Trial' },
    { section: 264, title: 'Conviction on plea of guilty', chapter: 'Chapter XXI: Warrant Cases Trial' },
    { section: 265, title: 'Evidence for prosecution', chapter: 'Chapter XXI: Warrant Cases Trial' },
    { section: 266, title: 'Evidence for defence', chapter: 'Chapter XXI: Warrant Cases Trial' },
    { section: 267, title: 'Evidence for prosecution in cases instituted otherwise than on police report', chapter: 'Chapter XXI: Warrant Cases Trial' },
    { section: 268, title: 'When accused shall be discharged', chapter: 'Chapter XXI: Warrant Cases Trial' },
    { section: 269, title: 'Procedure where accused is not discharged', chapter: 'Chapter XXI: Warrant Cases Trial' },
    { section: 270, title: 'Evidence for defence', chapter: 'Chapter XXI: Warrant Cases Trial' },
    { section: 271, title: 'Acquittal or conviction', chapter: 'Chapter XXI: Warrant Cases Trial' },
    { section: 272, title: 'Absence of complainant', chapter: 'Chapter XXI: Warrant Cases Trial' },
    { section: 273, title: 'Compensation for accusation without reasonable cause', chapter: 'Chapter XXI: Warrant Cases Trial' },
    { section: 274, title: 'Substance of accusation to be stated', chapter: 'Chapter XXII: Summons Cases Trial' },
    { section: 275, title: 'Conviction on plea of guilty', chapter: 'Chapter XXII: Summons Cases Trial' },
    { section: 276, title: 'Conviction on plea of guilty in absence of accused in petty cases', chapter: 'Chapter XXII: Summons Cases Trial' },
    { section: 277, title: 'Procedure when not convicted', chapter: 'Chapter XXII: Summons Cases Trial' },
    { section: 278, title: 'Acquittal or conviction', chapter: 'Chapter XXII: Summons Cases Trial' },
    { section: 279, title: 'Non-appearance or death of complainant', chapter: 'Chapter XXII: Summons Cases Trial' },
    { section: 280, title: 'Withdrawal of complaint', chapter: 'Chapter XXII: Summons Cases Trial' },
    { section: 281, title: 'Power to stop proceedings in certain cases', chapter: 'Chapter XXII: Summons Cases Trial' },
    { section: 282, title: 'Power of Court to convert summons-cases into warrant-cases', chapter: 'Chapter XXII: Summons Cases Trial' },
    { section: 283, title: 'Power to try summarily', chapter: 'Chapter XXIII: Summary Trials' },
    { section: 284, title: 'Summary trial by Magistrate of second class', chapter: 'Chapter XXIII: Summary Trials' },
    { section: 285, title: 'Procedure for summary trials', chapter: 'Chapter XXIII: Summary Trials' },
    { section: 286, title: 'Record in summary trials', chapter: 'Chapter XXIII: Summary Trials' },
    { section: 287, title: 'Judgment in cases tried summarily', chapter: 'Chapter XXIII: Summary Trials' },
    { section: 288, title: 'Language of record and judgment', chapter: 'Chapter XXIII: Summary Trials' },
    { section: 289, title: 'Application of Chapter', chapter: 'Chapter XXIV: Plea Bargaining' },
    { section: 290, title: 'Application for plea bargaining', chapter: 'Chapter XXIV: Plea Bargaining' },
    { section: 291, title: 'Guidelines for mutually satisfactory disposition', chapter: 'Chapter XXIV: Plea Bargaining' },
    { section: 292, title: 'Report of mutually satisfactory disposition to Court', chapter: 'Chapter XXIV: Plea Bargaining' },
    { section: 293, title: 'Disposal of case under plea bargaining', chapter: 'Chapter XXIV: Plea Bargaining' },
    { section: 294, title: 'Judgment of Court in plea bargaining', chapter: 'Chapter XXIV: Plea Bargaining' },
    { section: 295, title: 'Finality of judgment', chapter: 'Chapter XXIV: Plea Bargaining' },
    { section: 296, title: 'Power of Court in plea bargaining', chapter: 'Chapter XXIV: Plea Bargaining' },
    { section: 297, title: 'Period of detention set off against sentence', chapter: 'Chapter XXIV: Plea Bargaining' },
    { section: 298, title: 'Savings', chapter: 'Chapter XXIV: Plea Bargaining' },
    { section: 299, title: 'Statements of accused not to be used', chapter: 'Chapter XXIV: Plea Bargaining' },
    { section: 300, title: 'Non-application of Chapter', chapter: 'Chapter XXIV: Plea Bargaining' },
    { section: 301, title: 'Definitions (Attendance of Prisoners)', chapter: 'Chapter XXV: Attendance of Prisoners' },
    { section: 302, title: 'Power to require attendance of prisoners', chapter: 'Chapter XXV: Attendance of Prisoners' },
    { section: 303, title: 'Power to exclude certain persons from section 302', chapter: 'Chapter XXV: Attendance of Prisoners' },
    { section: 304, title: 'Officer in charge of prison to abstain from carrying out order', chapter: 'Chapter XXV: Attendance of Prisoners' },
    { section: 305, title: 'Prisoner to be brought to Court in custody', chapter: 'Chapter XXV: Attendance of Prisoners' },
    { section: 306, title: 'Power to issue commission for examination of witness in prison', chapter: 'Chapter XXV: Attendance of Prisoners' },
    { section: 307, title: 'Language of Courts', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 308, title: 'Evidence to be taken in presence of accused', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 309, title: 'Record in summons-cases and inquiries', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 310, title: 'Record in warrant-cases', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 311, title: 'Record in trial before Court of Session', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 312, title: 'Language of record of evidence', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 313, title: 'Procedure in regard to evidence when completed', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 314, title: 'Interpretation of evidence to accused or advocate', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 315, title: 'Remarks respecting demeanour of witness', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 316, title: 'Record of examination of accused', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 317, title: 'Interpreter bound to interpret truthfully', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 318, title: 'Record in High Court', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 319, title: 'When attendance of witness dispensed with and commission issued', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 320, title: 'Commission to whom to be issued', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 321, title: 'Execution of commissions', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 322, title: 'Parties may examine witnesses', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 323, title: 'Return of commission', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 324, title: 'Adjournment of proceeding', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 325, title: 'Execution of foreign commissions', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 326, title: 'Deposition of medical witness', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 327, title: 'Identification report of Magistrate', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 328, title: 'Evidence of officers of Mint', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 329, title: 'Reports of certain Government scientific experts', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 330, title: 'No formal proof of certain documents (ELECTRONIC EVIDENCE PROOF)', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 331, title: 'Affidavit in proof of conduct of public servants', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 332, title: 'Evidence of formal character on affidavit', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 333, title: 'Authorities before whom affidavits may be sworn', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 334, title: 'Previous conviction or acquittal how proved', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 335, title: 'Record of evidence in absence of accused', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 336, title: 'Evidence of public servants, experts, police officers', chapter: 'Chapter XXVI: Evidence & Trial Rules' },
    { section: 337, title: 'Person once convicted or acquitted not to be tried for same offence (Double Jeopardy)', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 338, title: 'Appearance by Public Prosecutors', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 339, title: 'Permission to conduct prosecution', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 340, title: 'Right of person against whom proceedings instituted to be defended', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 341, title: 'Legal aid to accused at State expense', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 342, title: 'Procedure when corporation or registered society is accused', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 343, title: 'Tender of pardon to accomplice', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 344, title: 'Power to direct tender of pardon', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 345, title: 'Trial of person not complying with conditions of pardon', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 346, title: 'Power to postpone or adjourn proceedings', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 347, title: 'Local inspection', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 348, title: 'Power to summon material witness or examine person present', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 349, title: 'Power of Magistrate to order specimen signatures or handwriting', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 350, title: 'Expenses of complainants and witnesses', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 351, title: 'Power to examine accused', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 352, title: 'Oral arguments and memorandum of arguments', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 353, title: 'Accused person to be competent witness', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 354, title: 'No influence to be used to induce disclosure', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 355, title: 'Provision for inquiries and trial in absence of accused', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 356, title: 'Inquiry, trial or judgment in absentia of proclaimed offender', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 357, title: 'Procedure where accused does not understand proceedings', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 358, title: 'Power to proceed against other persons appearing guilty', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 359, title: 'Compounding of offences', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 360, title: 'Withdrawal from prosecution', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 361, title: 'Procedure in cases which Magistrate cannot dispose of', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 362, title: 'Procedure when Magistrate finds case should be committed', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 363, title: 'Trial of persons previously convicted of offences against coinage/property', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 364, title: 'Procedure when Magistrate cannot pass sentence sufficiently severe', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 365, title: 'Conviction on evidence partly recorded by one Magistrate and partly by another', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 366, title: 'Court to be open', chapter: 'Chapter XXVII: General Trial Provisions' },
    { section: 367, title: 'Procedure in case of accused being person of unsound mind', chapter: 'Chapter XXVIII: Unsound Mind Provisions' },
    { section: 368, title: 'Procedure in case of person of unsound mind tried before Court', chapter: 'Chapter XXVIII: Unsound Mind Provisions' },
    { section: 369, title: 'Release of person of unsound mind pending investigation or trial', chapter: 'Chapter XXVIII: Unsound Mind Provisions' },
    { section: 370, title: 'Resumption of inquiry or trial', chapter: 'Chapter XXVIII: Unsound Mind Provisions' },
    { section: 371, title: 'Procedure on accused appearing before Magistrate or Court', chapter: 'Chapter XXVIII: Unsound Mind Provisions' },
    { section: 372, title: 'When accused appears to have been of sound mind', chapter: 'Chapter XXVIII: Unsound Mind Provisions' },
    { section: 373, title: 'Judgment of acquittal on ground of unsoundness of mind', chapter: 'Chapter XXVIII: Unsound Mind Provisions' },
    { section: 374, title: 'Person acquitted on ground of unsoundness to be detained in safe custody', chapter: 'Chapter XXVIII: Unsound Mind Provisions' },
    { section: 375, title: 'Power of State Government to empower officer to discharge', chapter: 'Chapter XXVIII: Unsound Mind Provisions' },
    { section: 376, title: 'Procedure where prisoner of unsound mind is capable of defense', chapter: 'Chapter XXVIII: Unsound Mind Provisions' },
    { section: 377, title: 'Procedure where person detained is declared fit to be released', chapter: 'Chapter XXVIII: Unsound Mind Provisions' },
    { section: 378, title: 'Delivery of person of unsound mind to care of relative or friend', chapter: 'Chapter XXVIII: Unsound Mind Provisions' },
    { section: 379, title: 'Procedure in cases mentioned in section 215', chapter: 'Chapter XXVIII: Unsound Mind Provisions' },
    { section: 380, title: 'Appeal against order of unsoundness detention', chapter: 'Chapter XXVIII: Unsound Mind Provisions' },
    { section: 381, title: 'Power to order costs', chapter: 'Chapter XXIX: Administration of Justice' },
    { section: 382, title: 'Procedure of Magistrate taking cognizance', chapter: 'Chapter XXIX: Administration of Justice' },
    { section: 383, title: 'Summary procedure for trial for giving false evidence (Perjury)', chapter: 'Chapter XXIX: Administration of Justice' },
    { section: 384, title: 'Procedure in certain cases of contempt', chapter: 'Chapter XXIX: Administration of Justice' },
    { section: 385, title: 'Procedure where Court considers case should not be dealt under Sec 384', chapter: 'Chapter XXIX: Administration of Justice' },
    { section: 386, title: 'When Registrar to be deemed Civil Court', chapter: 'Chapter XXIX: Administration of Justice' },
    { section: 387, title: 'Discharge of offender on submission of apology', chapter: 'Chapter XXIX: Administration of Justice' },
    { section: 388, title: 'Imprisonment of person refusing to answer or produce document', chapter: 'Chapter XXIX: Administration of Justice' },
    { section: 389, title: 'Summary procedure for punishment for non-attendance by witness', chapter: 'Chapter XXIX: Administration of Justice' },
    { section: 390, title: 'Appeals from convictions under sections 383, 384, 388 and 389', chapter: 'Chapter XXIX: Administration of Justice' },
    { section: 391, title: 'Judges/Magistrates not to try offences committed before themselves', chapter: 'Chapter XXIX: Administration of Justice' },
    { section: 392, title: 'Judgment delivery and contents', chapter: 'Chapter XXX: The Judgment' },
    { section: 393, title: 'Language and contents of judgment', chapter: 'Chapter XXX: The Judgment' },
    { section: 394, title: 'Order for notifying address of previously convicted offender', chapter: 'Chapter XXX: The Judgment' },
    { section: 395, title: 'Order to pay compensation', chapter: 'Chapter XXX: The Judgment' },
    { section: 396, title: 'Victim Compensation Scheme (MANDATORY LEGISLATIVE SCHEME)', chapter: 'Chapter XXX: The Judgment (VICTIM RIGHTS)' },
    { section: 397, title: 'Treatment of victims of crime and free medical aid', chapter: 'Chapter XXX: The Judgment' },
    { section: 398, title: 'Witness Protection Scheme (MANDATORY STATE SCHEME)', chapter: 'Chapter XXX: The Judgment (WITNESS PROTECTION)' },
    { section: 399, title: 'Compensation to persons groundlessly arrested', chapter: 'Chapter XXX: The Judgment' },
    { section: 400, title: 'Order to pay costs in non-cognizable cases', chapter: 'Chapter XXX: The Judgment' },
    { section: 401, title: 'Order to release on probation of good conduct or after admonition', chapter: 'Chapter XXX: The Judgment' },
    { section: 402, title: 'Special reasons to be recorded in certain cases', chapter: 'Chapter XXX: The Judgment' },
    { section: 403, title: 'Court not to alter judgment', chapter: 'Chapter XXX: The Judgment' },
    { section: 404, title: 'Copy of judgment to be given to accused and victim', chapter: 'Chapter XXX: The Judgment' },
    { section: 405, title: 'Judgment when to be translated', chapter: 'Chapter XXX: The Judgment' },
    { section: 406, title: 'Sessions Court to send copy of finding to District Magistrate', chapter: 'Chapter XXX: The Judgment' },
    { section: 407, title: 'Sentence of death to be submitted for confirmation', chapter: 'Chapter XXXI: Death Sentence Confirmation' },
    { section: 408, title: 'Power to direct further inquiry or additional evidence', chapter: 'Chapter XXXI: Death Sentence Confirmation' },
    { section: 409, title: 'Power of High Court to confirm sentence or annul conviction', chapter: 'Chapter XXXI: Death Sentence Confirmation' },
    { section: 410, title: 'Confirmation or new sentence to be signed by two Judges', chapter: 'Chapter XXXI: Death Sentence Confirmation' },
    { section: 411, title: 'Procedure in case of difference of opinion', chapter: 'Chapter XXXI: Death Sentence Confirmation' },
    { section: 412, title: 'Procedure in cases submitted to High Court for confirmation', chapter: 'Chapter XXXI: Death Sentence Confirmation' },
    { section: 413, title: 'No appeal to lie unless otherwise provided', chapter: 'Chapter XXXII: Appeals' },
    { section: 414, title: 'Appeal from orders requiring security or rejecting surety', chapter: 'Chapter XXXII: Appeals' },
    { section: 415, title: 'Appeals from convictions', chapter: 'Chapter XXXII: Appeals' },
    { section: 416, title: 'No appeal in certain cases when accused pleads guilty', chapter: 'Chapter XXXII: Appeals' },
    { section: 417, title: 'No appeal in petty cases', chapter: 'Chapter XXXII: Appeals' },
    { section: 418, title: 'Appeal by State Government against sentence', chapter: 'Chapter XXXII: Appeals' },
    { section: 419, title: 'Appeal in case of acquittal', chapter: 'Chapter XXXII: Appeals' },
    { section: 420, title: 'Appeal against conviction by High Court in certain cases', chapter: 'Chapter XXXII: Appeals' },
    { section: 421, title: 'Special right of appeal in certain cases', chapter: 'Chapter XXXII: Appeals' },
    { section: 422, title: 'Appeal to Court of Session how heard', chapter: 'Chapter XXXII: Appeals' },
    { section: 423, title: 'Petition of appeal', chapter: 'Chapter XXXII: Appeals' },
    { section: 424, title: 'Procedure when appellant in jail', chapter: 'Chapter XXXII: Appeals' },
    { section: 425, title: 'Summary dismissal of appeal', chapter: 'Chapter XXXII: Appeals' },
    { section: 426, title: 'Procedure for hearing appeals not dismissed summarily', chapter: 'Chapter XXXII: Appeals' },
    { section: 427, title: 'Powers of Appellate Court', chapter: 'Chapter XXXII: Appeals' },
    { section: 428, title: 'Judgments of subordinate Appellate Court', chapter: 'Chapter XXXII: Appeals' },
    { section: 429, title: 'Order of High Court on appeal to be certified to lower Court', chapter: 'Chapter XXXII: Appeals' },
    { section: 430, title: 'Suspension of sentence pending appeal; release on bail', chapter: 'Chapter XXXII: Appeals' },
    { section: 431, title: 'Arrest of accused in appeal from acquittal', chapter: 'Chapter XXXII: Appeals' },
    { section: 432, title: 'Appellate Court may take further evidence', chapter: 'Chapter XXXII: Appeals' },
    { section: 433, title: 'Procedure where Judges of Court of appeal are equally divided', chapter: 'Chapter XXXII: Appeals' },
    { section: 434, title: 'Finality of judgments and orders on appeal', chapter: 'Chapter XXXII: Appeals' },
    { section: 435, title: 'Abatement of appeals', chapter: 'Chapter XXXII: Appeals' },
    { section: 436, title: 'Reference to High Court', chapter: 'Chapter XXXIII: Reference & Revision' },
    { section: 437, title: 'Disposal of case according to decision of High Court', chapter: 'Chapter XXXIII: Reference & Revision' },
    { section: 438, title: 'Calling for records to exercise powers of revision', chapter: 'Chapter XXXIII: Reference & Revision' },
    { section: 439, title: 'Power to order inquiry', chapter: 'Chapter XXXIII: Reference & Revision' },
    { section: 440, title: 'Sessions Judge powers of revision', chapter: 'Chapter XXXIII: Reference & Revision' },
    { section: 441, title: 'Power of Additional Sessions Judge', chapter: 'Chapter XXXIII: Reference & Revision' },
    { section: 442, title: 'High Court powers of revision', chapter: 'Chapter XXXIII: Reference & Revision' },
    { section: 443, title: 'Power of High Court to withdraw or transfer revision cases', chapter: 'Chapter XXXIII: Reference & Revision' },
    { section: 444, title: 'Option of Court to hear parties', chapter: 'Chapter XXXIII: Reference & Revision' },
    { section: 445, title: 'High Court order to be certified to lower Court', chapter: 'Chapter XXXIII: Reference & Revision' },
    { section: 446, title: 'Power of Supreme Court to transfer cases and appeals', chapter: 'Chapter XXXIV: Transfer of Cases' },
    { section: 447, title: 'Power of High Court to transfer cases and appeals', chapter: 'Chapter XXXIV: Transfer of Cases' },
    { section: 448, title: 'Power of Sessions Judge to transfer cases and appeals', chapter: 'Chapter XXXIV: Transfer of Cases' },
    { section: 449, title: 'Withdrawal of cases and appeals by Sessions Judges', chapter: 'Chapter XXXIV: Transfer of Cases' },
    { section: 450, title: 'Withdrawal of cases by Judicial Magistrates', chapter: 'Chapter XXXIV: Transfer of Cases' },
    { section: 451, title: 'Making over or withdrawal of cases by Executive Magistrates', chapter: 'Chapter XXXIV: Transfer of Cases' },
    { section: 452, title: 'Reasons to be recorded', chapter: 'Chapter XXXIV: Transfer of Cases' },
    { section: 453, title: 'Execution of order passed under section 409', chapter: 'Chapter XXXV: Execution of Sentences' },
    { section: 454, title: 'Execution of sentence of death passed by High Court', chapter: 'Chapter XXXV: Execution of Sentences' },
    { section: 455, title: 'Postponement of execution of death sentence in Supreme Court appeal', chapter: 'Chapter XXXV: Execution of Sentences' },
    { section: 456, title: 'Commutation of sentence of death on pregnant woman', chapter: 'Chapter XXXV: Execution of Sentences' },
    { section: 457, title: 'Power to appoint place of imprisonment', chapter: 'Chapter XXXV: Execution of Sentences' },
    { section: 458, title: 'Execution of sentence of imprisonment', chapter: 'Chapter XXXV: Execution of Sentences' },
    { section: 459, title: 'Direction of warrant for execution', chapter: 'Chapter XXXV: Execution of Sentences' },
    { section: 460, title: 'Warrant with whom to be lodged', chapter: 'Chapter XXXV: Execution of Sentences' },
    { section: 461, title: 'Warrant for levy of fine', chapter: 'Chapter XXXV: Execution of Sentences' },
    { section: 462, title: 'Effect of such warrant', chapter: 'Chapter XXXV: Execution of Sentences' },
    { section: 463, title: 'Warrant for levy of fine issued by Court outside territory', chapter: 'Chapter XXXV: Execution of Sentences' },
    { section: 464, title: 'Suspension of execution of sentence of imprisonment', chapter: 'Chapter XXXV: Execution of Sentences' },
    { section: 465, title: 'Who may issue warrant', chapter: 'Chapter XXXV: Execution of Sentences' },
    { section: 466, title: 'Sentence on escaped convict when to take effect', chapter: 'Chapter XXXV: Execution of Sentences' },
    { section: 467, title: 'Sentence on offender already sentenced for another offence', chapter: 'Chapter XXXV: Execution of Sentences' },
    { section: 468, title: 'Period of detention set off against sentence of imprisonment', chapter: 'Chapter XXXV: Execution of Sentences' },
    { section: 469, title: 'Saving clause', chapter: 'Chapter XXXV: Execution of Sentences' },
    { section: 470, title: 'Return of warrant on execution of sentence', chapter: 'Chapter XXXV: Execution of Sentences' },
    { section: 471, title: 'Money ordered to be paid recoverable as fine', chapter: 'Chapter XXXV: Execution of Sentences' },
    { section: 472, title: 'Mercy petition in death sentence cases', chapter: 'Chapter XXXVI: Mercy & Commutation' },
    { section: 473, title: 'Power to suspend or remit sentences', chapter: 'Chapter XXXVI: Mercy & Commutation' },
    { section: 474, title: 'Power to commute sentence', chapter: 'Chapter XXXVI: Mercy & Commutation' },
    { section: 475, title: 'Restriction on powers of remission or commutation in certain cases', chapter: 'Chapter XXXVI: Mercy & Commutation' },
    { section: 476, title: 'Concurrent power of Central Government in death sentences', chapter: 'Chapter XXXVI: Mercy & Commutation' },
    { section: 477, title: 'State Government to act after concurrence with Central Government', chapter: 'Chapter XXXVI: Mercy & Commutation' },
    { section: 478, title: 'In what cases bail to be taken (Bailable Offence Bail Right)', chapter: 'Chapter XXXVII: Bail & Bonds' },
    { section: 479, title: 'Maximum period for which under-trial prisoner can be detained', chapter: 'Chapter XXXVII: Bail & Bonds (UNDERTRIAL RIGHTS)' },
    { section: 480, title: 'When bail may be taken in non-bailable offence', chapter: 'Chapter XXXVII: Bail & Bonds' },
    { section: 481, title: 'Bail to require accused to appear before next Appellate Court', chapter: 'Chapter XXXVII: Bail & Bonds' },
    { section: 482, title: 'Direction for grant of bail to person apprehending arrest (Anticipatory Bail)', chapter: 'Chapter XXXVII: Bail & Bonds (ANTICIPATORY BAIL)' },
    { section: 483, title: 'Special powers of High Court or Sessions Court regarding bail', chapter: 'Chapter XXXVII: Bail & Bonds' },
    { section: 484, title: 'Amount of bond and reduction thereof', chapter: 'Chapter XXXVII: Bail & Bonds' },
    { section: 485, title: 'Bond of accused and sureties', chapter: 'Chapter XXXVII: Bail & Bonds' },
    { section: 486, title: 'Declaration by sureties', chapter: 'Chapter XXXVII: Bail & Bonds' },
    { section: 487, title: 'Discharge from custody on bail execution', chapter: 'Chapter XXXVII: Bail & Bonds' },
    { section: 488, title: 'Power to order sufficient bail when first taken insufficient', chapter: 'Chapter XXXVII: Bail & Bonds' },
    { section: 489, title: 'Discharge of sureties', chapter: 'Chapter XXXVII: Bail & Bonds' },
    { section: 490, title: 'Deposit instead of recognizance', chapter: 'Chapter XXXVII: Bail & Bonds' },
    { section: 491, title: 'Procedure when bond has been forfeited', chapter: 'Chapter XXXVII: Bail & Bonds' },
    { section: 492, title: 'Cancellation of bond and bail bond', chapter: 'Chapter XXXVII: Bail & Bonds' },
    { section: 493, title: 'Procedure in case of insolvency/death of surety or bond forfeiture', chapter: 'Chapter XXXVII: Bail & Bonds' },
    { section: 494, title: 'Bond required from child', chapter: 'Chapter XXXVII: Bail & Bonds' },
    { section: 495, title: 'Appeal from orders under section 491', chapter: 'Chapter XXXVII: Bail & Bonds' },
    { section: 496, title: 'Power to direct levy of amount due on recognizances', chapter: 'Chapter XXXVII: Bail & Bonds' },
    { section: 497, title: 'Order for custody and disposal of property pending trial', chapter: 'Chapter XXXVIII: Disposal of Property' },
    { section: 498, title: 'Order for disposal of property at conclusion of trial', chapter: 'Chapter XXXVIII: Disposal of Property' },
    { section: 499, title: 'Payment to innocent purchaser of money found on accused', chapter: 'Chapter XXXVIII: Disposal of Property' },
    { section: 500, title: 'Appeal against orders under section 498 or 499', chapter: 'Chapter XXXVIII: Disposal of Property' },
    { section: 501, title: 'Destruction of libellous and other matter', chapter: 'Chapter XXXVIII: Disposal of Property' },
    { section: 502, title: 'Power to restore possession of immovable property', chapter: 'Chapter XXXVIII: Disposal of Property' },
    { section: 503, title: 'Procedure by police upon seizure of property', chapter: 'Chapter XXXVIII: Disposal of Property' },
    { section: 504, title: 'Procedure where no claimant appears within six months', chapter: 'Chapter XXXVIII: Disposal of Property' },
    { section: 505, title: 'Power to sell perishable property', chapter: 'Chapter XXXVIII: Disposal of Property' },
    { section: 506, title: 'Irregularities which do not vitiate proceedings', chapter: 'Chapter XXXIX: Irregularities & Limitation' },
    { section: 507, title: 'Irregularities which vitiate proceedings', chapter: 'Chapter XXXIX: Irregularities & Limitation' },
    { section: 508, title: 'Proceedings in wrong place', chapter: 'Chapter XXXIX: Irregularities & Limitation' },
    { section: 509, title: 'Non-compliance with provisions of section 183 or section 316', chapter: 'Chapter XXXIX: Irregularities & Limitation' },
    { section: 510, title: 'Effect of omission to frame, or absence of, or error in, charge', chapter: 'Chapter XXXIX: Irregularities & Limitation' },
    { section: 511, title: 'Finding or sentence when reversible by reason of error/omission', chapter: 'Chapter XXXIX: Irregularities & Limitation' },
    { section: 512, title: 'Defect or error not to make attachment unlawful', chapter: 'Chapter XXXIX: Irregularities & Limitation' },
    { section: 513, title: 'Definitions (Period of Limitation)', chapter: 'Chapter XXXIX: Irregularities & Limitation' },
    { section: 514, title: 'Bar to taking cognizance after lapse of period of limitation', chapter: 'Chapter XXXIX: Irregularities & Limitation' },
    { section: 515, title: 'Commencement of period of limitation', chapter: 'Chapter XXXIX: Irregularities & Limitation' },
    { section: 516, title: 'Exclusion of time in certain cases', chapter: 'Chapter XXXIX: Irregularities & Limitation' },
    { section: 517, title: 'Exclusion of date on which Court is closed', chapter: 'Chapter XXXIX: Irregularities & Limitation' },
    { section: 518, title: 'Continuing offence', chapter: 'Chapter XXXIX: Irregularities & Limitation' },
    { section: 519, title: 'Extension of period of limitation in certain cases', chapter: 'Chapter XXXIX: Irregularities & Limitation' },
    { section: 520, title: 'Trials before High Courts', chapter: 'Chapter XL: Miscellaneous' },
    { section: 521, title: 'Delivery to commanding officers of persons liable to Court-martial', chapter: 'Chapter XL: Miscellaneous' },
    { section: 522, title: 'Official Forms under BNSS', chapter: 'Chapter XL: Miscellaneous' },
    { section: 523, title: 'Power of High Court to make rules', chapter: 'Chapter XL: Miscellaneous' },
    { section: 524, title: 'Power to alter functions allocated to Executive Magistrate', chapter: 'Chapter XL: Miscellaneous' },
    { section: 525, title: 'Cases in which Judge or Magistrate is personally interested', chapter: 'Chapter XL: Miscellaneous' },
    { section: 526, title: 'Practising advocate not to sit as Magistrate in certain Courts', chapter: 'Chapter XL: Miscellaneous' },
    { section: 527, title: 'Public servant concerned in sale not to purchase property', chapter: 'Chapter XL: Miscellaneous' },
    { section: 528, title: 'Saving of inherent powers of High Court (Old CrPC 482)', chapter: 'Chapter XL: Miscellaneous (INHERENT POWERS)' },
    { section: 529, title: 'Duty of High Court to exercise continuous superintendence', chapter: 'Chapter XL: Miscellaneous' },
    { section: 530, title: 'Trial and proceedings to be held in electronic mode', chapter: 'Chapter XL: Miscellaneous (ELECTRONIC MANDATE)' },
    { section: 531, title: 'Repeal and savings of Code of Criminal Procedure, 1973', chapter: 'Chapter XL: Miscellaneous' },
  ];

  const bnsPenalList = [
    { section: '303(2)', title: 'Theft', ipc: 'IPC Sec 379', punishment: 'Imprisonment up to 3 years, or fine, or both.', cognizable: 'Cognizable', bailable: 'Non-Bailable', court: 'Any Magistrate', details: 'Whoever intending to take dishonestly any movable property out of possession without consent moves that property.' },
    { section: '115(2)', title: 'Voluntarily Causing Hurt', ipc: 'IPC Sec 323', punishment: 'Imprisonment up to 1 year, or fine up to Rs 10,000, or both.', cognizable: 'Cognizable', bailable: 'Bailable', court: 'Any Magistrate', details: 'Whoever voluntarily causes bodily hurt to any person.' },
    { section: '309(4)', title: 'Robbery with Weapon Threat', ipc: 'IPC Sec 392', punishment: 'Rigorous imprisonment up to 10 years and fine.', cognizable: 'Cognizable', bailable: 'Non-Bailable', court: 'Session Court / Magistrate First Class', details: 'Theft accompanied by voluntary hurt, wrongful restraint, or threat of instant death/injury.' },
    { section: '318(4)', title: 'Cheating & Financial Fraud', ipc: 'IPC Sec 420', punishment: 'Imprisonment up to 7 years and fine.', cognizable: 'Cognizable', bailable: 'Non-Bailable', court: 'Magistrate First Class', details: 'Cheating and thereby dishonestly inducing delivery of property or alteration of valuable security.' },
    { section: '103(1)', title: 'Murder', ipc: 'IPC Sec 302', punishment: 'Death penalty or Life Imprisonment, and fine.', cognizable: 'Cognizable', bailable: 'Non-Bailable', court: 'Court of Session', details: 'Causing death with intention or knowledge that act is so imminently dangerous it must cause death.' },
    { section: '109', title: 'Attempt to Murder', ipc: 'IPC Sec 307', punishment: 'Imprisonment up to 10 years and fine; if hurt caused, life imprisonment.', cognizable: 'Cognizable', bailable: 'Non-Bailable', court: 'Court of Session', details: 'Act done with intention or knowledge that if death was caused, offender would be guilty of murder.' },
    { section: '117(2)', title: 'Voluntarily Causing Grievous Hurt', ipc: 'IPC Sec 325', punishment: 'Imprisonment up to 7 years and fine.', cognizable: 'Cognizable', bailable: 'Non-Bailable', court: 'Magistrate First Class', details: 'Causes permanent privation of sight/hearing, bone fracture, or bodily pain for 20 days.' },
    { section: '319(2)', title: 'Cyber Fraud & Impersonation', ipc: 'IPC Sec 419', punishment: 'Imprisonment up to 5 years, or fine, or both.', cognizable: 'Cognizable', bailable: 'Non-Bailable', court: 'Any Magistrate', details: 'Cheating by pretending to be another person or using computer system/OTP fraudulently.' },
    { section: '351(2)', title: 'Criminal Intimidation', ipc: 'IPC Sec 506', punishment: 'Imprisonment up to 2 years, or fine, or both.', cognizable: 'Cognizable', bailable: 'Bailable', court: 'Any Magistrate', details: 'Threatening another with injury to person, reputation or property to cause alarm.' },
    { section: '85', title: 'Cruelty by Husband or Relatives for Dowry', ipc: 'IPC Sec 498A', punishment: 'Imprisonment up to 3 years and fine.', cognizable: 'Cognizable', bailable: 'Non-Bailable', court: 'Magistrate First Class', details: 'Subjecting a woman to cruelty or harassment to coerce her or relatives for dowry.' },
  ];

  const filteredBNSS = bnssAllSections.filter(
    (b) => b.section.toString() === searchTerm.trim() || b.title.toLowerCase().includes(searchTerm.toLowerCase()) || b.chapter.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const filteredBNS = bnsPenalList.filter(
    (b) => b.section.toLowerCase().includes(searchTerm.toLowerCase()) || b.title.toLowerCase().includes(searchTerm.toLowerCase())
  );

  if (!isOpen) return null;

  return (
    <div style={{
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      background: 'rgba(0,0,0,0.85)',
      backdropFilter: 'blur(10px)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 2000,
      padding: '20px',
    }}>
      <div className="glass-card" style={{ width: '920px', maxHeight: '88vh', padding: '28px', overflowY: 'auto', border: '1px solid var(--border-gold)' }}>
        <div className="flex-between" style={{ marginBottom: '16px' }}>
          <div>
            <h3 style={{ fontSize: '1.4rem', fontWeight: 800, display: 'flex', alignItems: 'center', gap: '10px', color: 'var(--primary-gold)' }}>
              <BookOpen size={24} /> Bharatiya Nagarik Suraksha Sanhita, 2023 (Complete 531-Section Codebook)
            </h3>
            <p style={{ fontSize: '0.82rem', color: 'var(--text-muted)', marginTop: '2px' }}>
              Official Judicial Gazette Index • BNSS 2023 Procedural Code (Sections 1 to 531) & BNS 2023 Substantive Law
            </p>
          </div>
          <button onClick={onClose} style={{ background: 'none', border: 'none', color: '#fff', cursor: 'pointer' }}>
            <X size={24} />
          </button>
        </div>

        <div style={{ display: 'flex', gap: '10px', marginBottom: '16px' }}>
          <button
            onClick={() => setSelectedTab('BNSS_PROCEDURAL')}
            className={`btn-secondary ${selectedTab === 'BNSS_PROCEDURAL' ? 'glass-card-gold' : ''}`}
            style={{ flex: 1, justifyContent: 'center' }}
          >
            <FileText size={16} /> BNSS 2023 Procedural Code (All 531 Sections)
          </button>
          <button
            onClick={() => setSelectedTab('BNS_PENAL')}
            className={`btn-secondary ${selectedTab === 'BNS_PENAL' ? 'glass-card-gold' : ''}`}
            style={{ flex: 1, justifyContent: 'center' }}
          >
            <Scale size={16} /> BNS 2023 Substantive Penal Codes
          </button>
        </div>

        <div style={{ position: 'relative', marginBottom: '16px' }}>
          <Search size={16} style={{ position: 'absolute', left: '12px', top: '12px', color: 'var(--text-muted)' }} />
          <input
            type="text"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            placeholder="Type section number (e.g. 173, 176, 482, 530) or legal term (FIR, Bail, Arrest, Electronic)..."
            style={{
              width: '100%',
              padding: '10px 10px 10px 38px',
              background: 'rgba(0,0,0,0.4)',
              border: '1px solid var(--border-card)',
              borderRadius: '8px',
              color: '#fff',
              outline: 'none',
              fontSize: '0.88rem'
            }}
          />
        </div>

        {selectedTab === 'BNSS_PROCEDURAL' ? (
          <div>
            <div style={{ fontSize: '0.8rem', color: 'var(--primary-gold)', marginBottom: '10px', fontWeight: 600 }}>
              Showing {filteredBNSS.length} of 531 Sections in BNSS 2023 Codebook Index:
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', maxHeight: '520px', overflowY: 'auto' }}>
              {filteredBNSS.map((sec) => (
                <div key={sec.section} style={{ background: 'rgba(0,0,0,0.3)', border: '1px solid var(--border-card)', padding: '10px 14px', borderRadius: '8px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <div>
                    <span style={{ fontWeight: 800, color: 'var(--primary-gold)', fontSize: '0.92rem', marginRight: '10px' }}>
                      BNSS Section {sec.section}
                    </span>
                    <span style={{ color: '#fff', fontSize: '0.88rem' }}>{sec.title}</span>
                  </div>
                  <span className="badge badge-gold" style={{ fontSize: '0.7rem' }}>{sec.chapter}</span>
                </div>
              ))}
            </div>
          </div>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            {filteredBNS.map((bns, idx) => (
              <div key={idx} style={{ background: 'rgba(0,0,0,0.35)', border: '1px solid var(--border-card)', padding: '14px', borderRadius: '10px' }}>
                <div className="flex-between">
                  <span style={{ fontWeight: 800, color: 'var(--primary-gold)', fontSize: '1rem' }}>
                    BNS Section {bns.section} - {bns.title}
                  </span>
                  <div style={{ display: 'flex', gap: '6px' }}>
                    <span className="badge badge-gold">{bns.ipc}</span>
                    <span className={`badge ${bns.bailable === 'Bailable' ? 'badge-success' : 'badge-danger'}`}>{bns.bailable}</span>
                    <span className="badge badge-warning">{bns.cognizable}</span>
                  </div>
                </div>

                <p style={{ fontSize: '0.82rem', color: '#e2e8f0', marginTop: '6px' }}>{bns.details}</p>

                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px', marginTop: '8px', fontSize: '0.78rem', color: 'var(--text-muted)', background: 'rgba(0,0,0,0.3)', padding: '8px', borderRadius: '6px' }}>
                  <div><strong>Punishment:</strong> {bns.punishment}</div>
                  <div><strong>Court of Trial:</strong> {bns.court}</div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};
